
[hikyuu]
tmpdir = ../data/tmp
datadir = ../data
quotation_server = ipc:///tmp/hikyuu_real.ipc

[block]
type = sqlite3
db = ../data/stock.db
;type  = qianlong
;dir = ../data/block
;指数板块 = zsbk.ini
;行业板块 = hybk.ini
;地域板块 = dybk.ini
;概念板块 = gnbk.ini
;self = self.ini

[preload]
day = True
week = True
month = True
quarter = True
halfyear = True
year = True
min = False
min5 = False
min15 = False
min30 = True
min60 = True
hour2= True
day_max = 100000
week_max = 100000
month_max = 100000
quarter_max = 100000
halfyear_max = 100000
year_max = 100000
min_max = 5120
min5_max = 5120
min15_max = 5120
min30_max = 5120
min60_max = 5120
hour2_max = 5120

[baseinfo]
type = sqlite3
db = E:/AA_CCODE/aiagents-stock-jaxdd/data/stock.db

[kdata]
;type = tdx
;dir = D:\TdxW_HuaTai\vipdoc
type = hdf5
sh_day = ../data/sh_day.h5
sh_min = ../data/sh_1min.h5
sh_min5 = ../data/sh_5min.h5
sz_day = ../data/sz_day.h5
sz_min = ../data/sz_1min.h5
sz_min5 = ../data/sz_5min.h5
sh_time = ../data/sh_time.h5
sz_time = ../data/sz_time.h5
sh_trans = ../data/sh_trans.h5
sz_trans = ../data/sz_trans.h5
bj_day = ../data/bj_day.h5
bj_min = ../data/bj_1min.h5
bj_min5 = ../data/bj_5min.h5
bj_time = ../data/bj_time.h5
bj_trans = ../data/bj_trans.h5
